<a href="https://colab.research.google.com/github/Juuuuls/CPE311/blob/main/Seatwork_6_1_QUIBRAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Seatwork 6.1 Exploratory Data Analysis on Your Own Dataset**

CPE311 Computational Thinking with Python

**Name:** Quibral, Juliann Vincent B.

**Section:** CPE22S3

**Performed on:** 03/11/2024

**Submitted on:** 03/11/2024

**Submitted to:** Engr. Roman M. Richard

In [20]:
file_path = "/content/delivery.csv"

In [21]:
import numpy as np
import pandas as pd

In [22]:
data = pd.read_csv(file_path)

In [23]:
data

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10994,10995,A,Ship,4,1,252,5,medium,F,1,1538,1
10995,10996,B,Ship,4,1,232,5,medium,F,6,1247,0
10996,10997,C,Ship,5,4,242,5,low,F,4,1155,0
10997,10998,F,Ship,5,2,223,6,medium,M,2,1210,0
10998,10999,D,Ship,2,5,155,5,low,F,6,1639,0

**1.Data set column names**

In [24]:
column_names = data.columns
print("Column Names:", column_names)

Column Names: Index(['ID', 'Warehouse_block', 'Mode_of_Shipment', 'Customer_care_calls',
       'Customer_rating', 'Cost_of_the_Product', 'Prior_purchases',
       'Product_importance', 'Gender', 'Discount_offered', 'Weight_in_gms',
       'Reached.on.Time_Y.N'],
      dtype='object')

**2. Data set data types**

In [25]:
data_types = data.dtypes
print("\nData Types:\n", data_types)

Data Types:
 ID                      int64
Warehouse_block        object
Mode_of_Shipment       object
Customer_care_calls     int64
Customer_rating         int64
Cost_of_the_Product     int64
Prior_purchases         int64
Product_importance     object
Gender                 object
Discount_offered        int64
Weight_in_gms           int64
Reached.on.Time_Y.N     int64
dtype: object

**3. Total number of records**

In [26]:
total_records = len(data)
print("\nTotal Number of Records:", total_records)

Total Number of Records: 10999

**4. Display the first**

In [32]:
print("\n\nFirst 10 Records:")
print(data.head(10))

First 10 Records:
   ID Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0   1               D           Flight                    4                2
1   2               F           Flight                    4                5
2   3               A           Flight                    2                2
3   4               B           Flight                    3                3
4   5               C           Flight                    2                2
5   6               F           Flight                    3                1
6   7               D           Flight                    3                4
7   8               F           Flight                    4                1
8   9               A           Flight                    3                4
9  10               B           Flight                    3                2

   Cost_of_the_Product  Prior_purchases Product_importance Gender  \
0                  177                3                low      F
1                  216                2                low      M
2                  183                4                low      M
3                  176                4             medium      M
4                  184                3             medium      F
5                  162                3             medium      F
6                  250                3                low      F
7                  233                2                low      F
8                  150                3                low      F
9                  164                3             medium      F

   Discount_offered  Weight_in_gms  Reached.on.Time_Y.N
0                44           1233                    1
1                59           3088                    1
2                48           3374                    1
3                10           1177                    1
4                46           2484                    1
5                12           1417                    1
6                 3           2371                    1
7                48           2804                    1
8                11           1861                    1
9                29           1187                    1

**5. Display the last 20 of the record**

In [31]:
print("\n\nLast 10 Records:")
print(data.tail(10))

Last 10 Records:
          ID Warehouse_block Mode_of_Shipment  Customer_care_calls  \
10989  10990               B             Ship                    5
10990  10991               C             Ship                    5
10991  10992               F             Ship                    5
10992  10993               D             Ship                    5
10993  10994               F             Ship                    5
10994  10995               A             Ship                    4
10995  10996               B             Ship                    4
10996  10997               C             Ship                    5
10997  10998               F             Ship                    5
10998  10999               D             Ship                    2

       Customer_rating  Cost_of_the_Product  Prior_purchases  \
10989                1                  218                5
10990                4                  219                6
10991                2                  261                5
10992                1                  236                5
10993                1                  257                6
10994                1                  252                5
10995                1                  232                5
10996                4                  242                5
10997                2                  223                6
10998                5                  155                5

      Product_importance Gender  Discount_offered  Weight_in_gms  \
10989             medium      F                 9           1603
10990                low      M                 3           1098
10991             medium      M                 9           1227
10992             medium      M                 3           1906
10993                low      F                 1           1150
10994             medium      F                 1           1538
10995             medium      F                 6           1247
10996                low      F                 4           1155
10997             medium      M                 2           1210
10998                low      F                 6           1639

       Reached.on.Time_Y.N
10989                    0
10990                    0
10991                    1
10992                    0
10993                    0
10994                    1
10995                    0
10996                    0
10997                    0
10998                    0

In [33]:
data

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1
...,...,...,...,...,...,...,...,...,...,...,...,...
10994,10995,A,Ship,4,1,252,5,medium,F,1,1538,1
10995,10996,B,Ship,4,1,232,5,medium,F,6,1247,0
10996,10997,C,Ship,5,4,242,5,low,F,4,1155,0
10997,10998,F,Ship,5,2,223,6,medium,M,2,1210,0
10998,10999,D,Ship,2,5,155,5,low,F,6,1639,0

**6. Chnage the Product_importance column to Priority**

In [34]:
data.rename(columns={'Product_importance': 'Priority'}, inplace=True)

**7. Create a new column Classification**

In [35]:
data['Delivered.Late_Y.N'] = np.where(data['Reached.on.Time_Y.N'] == 0, 'Late', 'On Time')

**8. Create a new dataframe "lateDelivery"**

In [36]:
late_delivery = data[data['Reached.on.Time_Y.N'] == 0]

**9. Create a new dataframe "good_rating"**

In [37]:
good_rating = data[data['Customer_rating'] <= 3]

**10.Create a new dataframe "bad_rating"**

In [38]:
bad_rating = data[data['Customer_rating'] > 3]

In [39]:
data

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Priority,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N,Delivered.Late_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1,On Time
1,2,F,Flight,4,5,216,2,low,M,59,3088,1,On Time
2,3,A,Flight,2,2,183,4,low,M,48,3374,1,On Time
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1,On Time
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1,On Time
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10994,10995,A,Ship,4,1,252,5,medium,F,1,1538,1,On Time
10995,10996,B,Ship,4,1,232,5,medium,F,6,1247,0,Late
10996,10997,C,Ship,5,4,242,5,low,F,4,1155,0,Late
10997,10998,F,Ship,5,2,223,6,medium,M,2,1210,0,Late
10998,10999,D,Ship,2,5,155,5,low,F,6,1639,0,Late

**12. Use numpy to get the average cost and discount.**

In [40]:
average_cost = np.mean(data['Cost_of_the_Product'])
average_discount = np.mean(data['Discount_offered'])
print("\nAverage Cost:", average_cost)
print("Average Discount:", average_discount)

Average Cost: 210.19683607600692
Average Discount: 13.37321574688608

**13. Use numpy to get the median cost and discount.**

In [41]:
median_cost = np.median(data['Cost_of_the_Product'])
median_discount = np.median(data['Discount_offered'])
print("\nMedian Cost:", median_cost)
print("Median Discount:", median_discount)

Median Cost: 214.0
Median Discount: 7.0

**14. Use numpy to get the middle cost and discount.**

In [42]:
median_cost = np.median(np.sort(data['Cost_of_the_Product']))
median_discount = np.median(np.sort(data['Discount_offered']))
print("\nMiddle median:", median_cost)
print("Middle discount:", median_discount)

Middle median: 214.0
Middle discount: 7.0

**15. Use numpy to get the standard deviation of the discount_offered**

In [45]:
std_Discounts = np.std(data['Discount_offered'])
print("\nStandard Deviation of Discouns:", std_Discounts)

Standard Deviation of Discouns: 16.204790382056665

**Conclusion**

Upon doing the Seatwork and Hands on Activity data analysis tasks are the primary use case for Pandas. Working with numerical numbers is the primary usage of NumPy since it simplifies the application of mathematical functions. The pandas library functions effectively with both alphabetic and numeric data simultaneously. When doing logical and mathematical computations on arrays and matrices, NumPy is a great tool. Compared to Python lists, this utility completes these tasks substantially more quickly and effectively. The primary benefit of Numpy is its reduced memory and storage space use. In addition, Data alignment and integrated handling of missing data, data set merging and joining, data set reshaping and pivoting, label-based slicing, hierarchical axis indexing to work with high-dimensional data in a lower-dimensional data structure, and other advantages are also obtained from the Pandas library. With these tools data handling is made easier and more convenient.